// Normalize the official Berean Standard Bible export into the repo's
// LocalBibleVerse schema (src/lib/bibleText/bsbBibleVerses.ts).
//
// Source: https://bereanbible.com/bsb.txt — the official tab-separated
// plain-text export from the Berean Bible project, dedicated to the public
// domain. Text is copied verbatim (punctuation, quotes, capitalization);
// this script only reshapes it. Never hand-edit the generated file.
//
// Usage: node scripts/normalize-bsb.mjs path/to/bsb.txt
//
// The book/code/group/label vocabulary intentionally mirrors the existing
// WEB dataset (src/lib/bibleText/webusBibleVerses.ts) so both datasets are
// interchangeable behind src/lib/localBibleVerses.ts.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = process.argv[2];
if (!sourcePath) {
  console.error("Usage: node scripts/normalize-bsb.mjs path/to/bsb.txt");
  process.exit(1);
}

// Same book names, USFM codes, and lane groups the WEB dataset uses.
// BSB's export says "Psalm"; the app's canonical display name is "Psalms".
const webusModule = readFileSync(
  path.join(here, "../src/lib/bibleText/webusBibleVerses.ts"),
  "utf8",
);
const webusVerses = JSON.parse(
  webusModule.slice(webusModule.indexOf("= [") + 2, webusModule.lastIndexOf("];") + 1),
);
const bookInfo = new Map();
for (const verse of webusVerses) {
  if (!bookInfo.has(verse.book)) {
    bookInfo.set(verse.book, { code: verse.code, group: verse.group });
  }
}
const bookNameAliases = new Map([["Psalm", "Psalms"]]);

const lines = readFileSync(sourcePath, "utf8").replace(/^﻿/, "").split(/\r?\n/);
const verses = [];
for (const line of lines) {
  const tab = line.indexOf("\t");
  if (tab === -1) continue;
  const reference = line.slice(0, tab).trim();
  const text = line.slice(tab + 1).trim();
  const match = reference.match(/^(.+?) (\d+):(\d+)$/);
  if (!match || !text) continue;

  const book = bookNameAliases.get(match[1]) ?? match[1];
  const info = bookInfo.get(book);
  if (!info) {
    console.error(`Unknown book name in source: "${match[1]}" (${reference})`);
    process.exit(1);
  }
  verses.push({
    book,
    code: info.code,
    chapter: match[2],
    verse: match[3],
    label: `${book} ${match[2]}:${match[3]}`,
    text,
    group: info.group,
  });
}

// Parity checks against the WEB dataset: same 66 books, same chapter set.
const webChapters = new Set(webusVerses.map((v) => `${v.code}.${v.chapter}`));
const bsbChapters = new Set(verses.map((v) => `${v.code}.${v.chapter}`));
const missingChapters = [...webChapters].filter((key) => !bsbChapters.has(key));
const extraChapters = [...bsbChapters].filter((key) => !webChapters.has(key));
if (missingChapters.length || extraChapters.length) {
  console.error("Chapter mismatch.", { missingChapters, extraChapters });
  process.exit(1);
}
const webRefs = new Set(webusVerses.map((v) => `${v.code}.${v.chapter}.${v.verse}`));
const bsbRefs = new Set(verses.map((v) => `${v.code}.${v.chapter}.${v.verse}`));
const missingVerses = [...webRefs].filter((key) => !bsbRefs.has(key));
const extraVerses = [...bsbRefs].filter((key) => !webRefs.has(key));
console.log(`BSB verses: ${verses.length} (WEB has ${webusVerses.length})`);
console.log("In WEB but not BSB:", missingVerses);
console.log("In BSB but not WEB:", extraVerses);

const body = verses
  .map((verse) => "  " + JSON.stringify(verse, null, 4).replace(/\n\}$/, "\n  }").replace(/\n {4}/g, "\n    "))
  .join(",\n");
const output = `// Berean Standard Bible — generated by scripts/normalize-bsb.mjs from the
// official public-domain export at https://bereanbible.com/bsb.txt.
// Do not hand-edit; regenerate instead. Scripture text is verbatim.

import type { LocalBibleVerse } from "./types";

export const BSB_BIBLE_VERSES: LocalBibleVerse[] = [
${body}
];
`;
writeFileSync(path.join(here, "../src/lib/bibleText/bsbBibleVerses.ts"), output);
console.log("Wrote src/lib/bibleText/bsbBibleVerses.ts");
